In [1]:
import pandas as pd
import seaborn as sns

In [9]:
df = pd.read_csv("../data/manutencao_preditiva.csv", sep = ",")

In [ ]:
print("\n========== INSPEÇÃO INICIAL DO DATASET ===========")
print(f"-----> O Dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas")
print("\n\n-----> COLUNAS, TIPOS DE DADOS E DADOS AUSENTES:")
display(df.info())
print("\n-----> AMOSTRA DO DATASET:")
display(df.sample(10))
print("\n-----> ESTATÍSTICAS DESCRITIVAS:\n")
display(df.describe())
#print(f"\n-----> ENTRADAS NULAS POR COLUNA:\n{df.isnull().sum()}")

========== INSPEÇÃO INICIAL DO DATASET ===========
-----> O Dataset possui 10000 linhas e 14 colunas


-----> COLUNAS, TIPOS DE DADOS E DADOS AUSENTES:
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   udi                      10000 non-null  int64
 1   id_produto               10000 non-null  str
 2   tipo                     10000 non-null  str
 3   temperatura_ar_k         9500 non-null   float64
 4   temperatura_processo_k   9500 non-null   float64
 5   velocidade_rotacao_rpm   9500 non-null   float64
 6   torque_nm                9500 non-null   float64
 7   desgaste_ferramenta_min  10000 non-null  int64
 8   falha_maquina            10000 non-null  int64
 9   falha_twf                10000 non-null  int64
 10  falha_hdf                10000 non-null  int64
 11  falha_pwf                10000 non-null  int64
 12  falha_osf                10000 non-null  int64
 13  falha_rnf                10000 non-null  int64
dtypes: float64(4), int64(8), str(2)
memory usage: 1.1 MB

None

-----> AMOSTRA DO DATASET:

,udi,id_produto,tipo,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
8642,8643,M23502,M,297.5,308.4,1596.0,36.6,80,0,0,0,0,0,0
6680,6681,L53860,L,301.5,310.8,1417.0,49.7,5,0,0,0,0,0,0
8127,8128,M22987,M,NaN,NaN,NaN,NaN,38,0,0,0,0,0,0
2152,2153,M17012,M,299.3,308.8,1648.0,28.4,188,0,0,0,0,0,0
3843,3844,L51023,L,302.5,311.2,1227.0,60.1,167,0,0,0,0,0,0
5763,5764,H35177,H,301.8,311.2,1451.0,39.4,70,0,0,0,0,0,0
6145,6146,M21005,M,301.1,311.1,1436.0,41.8,156,0,0,0,0,0,0
3937,3938,L51117,L,302.5,311.5,1802.0,26.4,192,0,0,0,0,0,0
2326,2327,M17186,M,299.4,308.7,1487.0,52.6,205,0,0,0,0,0,0
4416,4417,M19276,M,302.6,310.4,1532.0,36.1,77,0,0,0,0,0,0

-----> ESTATÍSTICAS DESCRITIVAS:

,udi,temperatura_ar_k,temperatura_processo_k,velocidade_rotacao_rpm,torque_nm,desgaste_ferramenta_min,falha_maquina,falha_twf,falha_hdf,falha_pwf,falha_osf,falha_rnf
count,10000.00000,9500.000000,9500.000000,9500.000000,9500.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,5000.50000,300.002158,310.000895,1539.245263,39.974168,107.951000,0.033900,0.004600,0.011500,0.009500,0.009800,0.00190
std,2886.89568,2.001689,1.486432,180.273589,9.995453,63.654147,0.180981,0.067671,0.106625,0.097009,0.098514,0.04355
min,1.00000,295.300000,305.700000,1168.000000,3.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,2500.75000,298.300000,308.800000,1423.000000,33.100000,53.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
50%,5000.50000,300.100000,310.100000,1504.000000,40.100000,108.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
75%,7500.25000,301.500000,311.100000,1613.000000,46.700000,162.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
max,10000.00000,304.500000,313.800000,2886.000000,76.600000,253.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000

In [ ]:
sns.heatmap()

ValueError: could not convert string to float: 'M14860'